# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Cache-YAMLCache
version:      0.01
version_from: YAMLCache.pm
installdirs:  site
requires:
    Cache::Cache:                  0
    YAML:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
